### PR TITLE
Added secure and samesite cookie option to configuration

### PR DESCRIPTION
**Pull request by binoyudayan**
Secure and samesite in options and also in set cookie utility function.

### CODE REVIEW

**Comment by binoyudayan** [comment]
Hi 
Shall I fix it with django 1.9 and python 2.7 and make new pull request again? 

I'm making contribution to a project for the first time, please excuse me for the mistakes.

**Comment by bmihelac** [comment]
hi @binoyudayan and thanks for pull request. If you fix python travis error and push, commit will show here. Other than this it is good idea to create new branches patches and fixes.

**Comment by binoyudayan** [comment]
Hi @bmihelac 

I have resolved the issue with python 2.7 as well. Sorry for the delay.

**Comment by kenanmasri** [comment]
Thanks for the package I think you should have already merged this important issue before releasing 0.3.0

**Pull request closed without merging**
