### PR TITLE
Remove smart_str

### PR DESCRIPTION
**Pull request by some1ataplace**

### CODE REVIEW

**Comment by sergei-maertens** [comment]
Can you elaborate on what breaks by using `smart_str`? As far as I can see it still exists in Django 4.1 and isn't deprecated either.

**Comment by some1ataplace** [comment]
@sergei-maertens - I am not entirely sure if anything breaks. I just thought having smart_str() in the code was strange since you told me in the middleware PR that it was weird to even be there when we could have simply used str().

**Comment by sergei-maertens** [comment]
Right, it's been a while so I forgot about that 😛

I'm wondering now if this was somehow related with the bytestring setting
name.

Possibly we don't even need any string casting at all - something to look
into!

**Review by sergei-maertens — APPROVED** [review]
Took a look - I don't see any reason why we need explicit casting. The model field is a `models.CharField` so it'll always return a `str` already.

I'll get this merged.

**Comment by sergei-maertens** [comment]
Cherrypicked the patch in 6a817e06778de3480ba6d43009ce3ab5a19f8c82

**Pull request closed without merging**
